# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
##DEPENDNCIES FOR CI
 welcome: circleci/welcome-orb@0.4.1

jobs:
 print_me:
  docker:
    - image: circleci/node:13.8.0

  steps:
    - run: echo Omar W


 print_us:
  docker:
    - image: circleci/node:13.8.0

  steps:
    - run:
        name: "Echo an env as part of the project"
        command: |
         echo $Omar
workflows:
#LETS NAME THE WORKFLOW welcome
 welcome:
  jobs:
    -  welcome/run
    -  print_me
    -  print_us:
        requires:
          - "print_me"

